ALTER TABLE users
    ADD COLUMN updated BOOLEAN NOT NULL,
    ADD COLUMN created BOOLEAN NOT NULL;

ALTER TABLE contacts
    ADD COLUMN updated BOOLEAN NOT NULL,
    ADD COLUMN created BOOLEAN NOT NULL;